martijnvanbrummelen/nwipe

src/gui.c
This should fix 
https://github.com/martijnvanbrummelen/nwipe/issues/16
and
https://github.com/martijnvanbrummelen/nwipe/issues/15
=> Fix ETA not updating properly and bad total throughput display

src/context.h, src/nwipe.c
This is based on my testing back in March on v0.21.  I have not re-tested it on the current files but I expect it should work.
=> Last-odd-block detected patch

src/gui.c, src/method.c, src/method.h, src/options.c
Added verify method ( #126 )
Updated the logic in `nwipe_runmethod()` to fix issues #91 and #17
=> Added Verify Method

.github/workflows/ci.yml
Library version change, update prior to install to see if it fixes library install problem that was previously working.
=> Update ci.yml with apt-get update

src/device.c, src/gui.c, src/logging.c, src/nwipe.c
Move flush of logs into final cleanup function
Minor alteration to one or two error messages
=> Add error checking code to pthread_mutex_lock functions

README.md, src/gui.c
@PartialVolume I forgot to update the doc in the README, so here it is.
=> Updated zero-fill documentation.

.clang-format, .github/workflows/ci.yml, .github/workflows/ci_ubuntu-16.04.yml, Makefile.am, src/nwipe.c, src/nwipe.h
@PartialVolume first formatting pass, only addressing `nwipe.c` and `nwipe.h`.
=> Formatting pass 1

.clang-format, .github/workflows/ci.yml, .github/workflows/ci_ubuntu-16.04.yml, src/nwipe.c, src/nwipe.h, src/options.c, src/options.h
@PartialVolume second pass at formatting. I also activated format checking in the CI for those files that were formatted.
=> Formatting pass 2

README.md, man/nwipe.1, src/gui.c, src/method.c, src/method.h, src/options.c
The new method works as far as I can tell:
```
[2019/12/28 22:45:26] nwipe: notice: Invoking method 'HMG IS5 Enhanced' on device '/dev/loop0'.
[2019/12/28 22:45:26] nwipe: notice: Starting round 1 of 1 on device '/dev/loop0'.
[2019/12/28 22:45:26] nwipe: notice: Starting pass 1 of 3, round 1 of 1, on device '/dev/loop0'.
[2019/12/28 22:45:27] nwipe: notice: 104857600 bytes written to device '/dev/loop0'.
[2019/12/28 22:45:27] nwipe: notice: Finished pass 1 of 3, round 1 of 1, on device '/dev/loop0'.
[2019/12/28 22:45:27] nwipe: notice: Starting pass 2 of 3, round 1 of 1, on device '/dev/loop0'.
[2019/12/28 22:45:27] nwipe: notice: 104857600 bytes written to device '/dev/loop0'.
[2019/12/28 22:45:27] nwipe: notice: Finished pass 2 of 3, round 1 of 1, on device '/dev/loop0'.
[2019/12/28 …
```
=> add HMG IS5 enhanced and make minor fixups

src/gui.c, src/method.c, src/method.h, src/pass.c
Also fixes OPSII method.
Place round_size calculation in the function calculate_round_size()
=> Fix percentage complete calculation for all methods

.github/workflows/ci.yml, .github/workflows/ci_ubuntu-16.04.yml, src/method.c, src/method.h, src/version.c, src/version.h
@PartialVolume another pass of formatting
=> formatting method and version module.

.github/workflows/ci.yml, .github/workflows/ci_ubuntu-16.04.yml, src/context.h
@PartialVolume another formatting PR, only for the `context.h` module this time.
=> Formatting context.h

.github/workflows/ci.yml, .github/workflows/ci_ubuntu-16.04.yml, src/device.c, src/device.h
@PartialVolume an easy one: formatting the device module.
=> Formatting device module.

.github/workflows/ci.yml, .github/workflows/ci_ubuntu-16.04.yml, src/prng.c, src/prng.h
@PartialVolume we're getting there !
=> Formatting prng module.

.github/workflows/ci.yml, .github/workflows/ci_ubuntu-16.04.yml, src/logging.c, src/logging.h
@PartialVolume this one really needed a formatting
=> Formatting pass 8

.github/workflows/ci.yml, .github/workflows/ci_ubuntu-16.04.yml, src/gui.c, src/gui.h, src/nwipe.c
@PartialVolume this is the last one!
=> Formatting gui module.

src/method.c
=> Fix percentage calculation for IS5 only

.github/workflows/ci_ubuntu_16.04.yml, .github/workflows/ci_ubuntu_latest.yml, README.md
Making sure we're using snake case for the workflow names.
=> Normalizing workflow names.

CHANGELOG.md, configure.ac, man/nwipe.1, src/gui.c, src/nwipe.c, src/nwipe.h, src/options.c, src/options.h, src/version.c
1. Add --autopoweroff option
2. Fix non working --nowait option.
3. Update version info to 0.29-release candidate
Closes #42
=> Add auto poweroff

README.md
=> Adding version badge to README.

src/device.c
This is mainly required for Debian sid if using
su instead of su - to run nwipe.
=> Search extra directories for smartctl & readlink

src/gui.c, src/gui.h, src/logging.c
Benefits include:
1. Standard fixed width output for disk
throughput, combined throughput and disk
capacity. Allows for better column alignment
when wiping multiple drives.
2. Removal of about 40 lines of duplicated code.
=> Use nwipe's nomenclature function

README.md
Build of ShredOS and download link with the latest nwipe master.
=> Update README.md ShredOS download with nwipe master

src/nwipe.c
=> Fix memory leak

README.md
Update the example gif and add some explanatory text to README.md
=> Update the example gif

src/gui.c, src/version.c
=> Fix incorrect footer message during wipe

src/options.c, src/options.h
=> Fix --sync option

.github/workflows/ci_formatting.yml, .github/workflows/ci_ubuntu_latest.yml
Fixes https://github.com/martijnvanbrummelen/nwipe/issues/222
=> Moving formatting to a new GH action.

src/nwipe.c
=> Fixes musl libc compatibility on NixOS issue #275

README.md
To official website of SystemRescue (also known as SystemRescueCd).
=> Correct one external link in README.md

src/method.c, src/options.c, src/prng.c
This PR commits the result of running `make format`.
It makes no other changes.
Signed-off-by: Andrew V. Jones <andrewvaughanj@gmail.com>
=> Run 'make format'

src/prng.c, src/version.c
Logs the specific prng that is initialised.
=> Logs the specific prng that is initialised.

configure.ac, man/nwipe.1, src/version.c
Update nwipe to 0.31 ready for release.
=> Update to 0.31

src/device.c
Add 'LU WWN ID' to the list of data returned
by smartctl that should be anonymized when
-q or --quiet is specified.
=> Anonymize 'LU WWN ID' when -q specified.

src/options.c
* added additional info for -q, i.e. what data is being removed from GUI and logs
* removed superfluous new line break
=> Update options.c with additional infor for -q

README.md, src/context.h, src/nwipe.c, src/version.c
=> Fix nwipe log format specifier incorrect

src/nwipe.c, src/nwipe.h, src/version.c
Check for specific errors.
Add retry loop with timeout for pthread_join.
=> Improve thread cancellation error reporting

man/nwipe.1, src/options.c
Reverts martijnvanbrummelen/nwipe#401
=> Revert "Isaac64, update options, help and man page"

.github/workflows/ci_formatting.yml, src/Makefile.am, src/PDFGen/pdfgen.c, src/PDFGen/pdfgen.h, src/create_pdf.c, src/create_pdf.h, src/nwipe.c, src/prng.c
This is the initial PR that contains code that creates a PDF Disk Erase Report unpopulated template. Currently a PDF file called output.pdf will be created each time nwipe is started.
There will be further commits that populate the erasure report on completion of the disk wipe.
More code to follow !
=> Create PDF Disk Erasure Report for each drive wiped (Initial code, more to come)

src/PDFGen/pdfgen.h, src/create_pdf.c, src/create_pdf.h, src/logging.c, src/nwipe.c
PDFGen3 - further work on PDF certificate
1. Changed most titles in certificate to gray with
the data in black.
Started adding real data to template including:
Model, serial no., method, verify, size.
more code to follow...
=> PDFGen3 - further work on PDF certificate

src/context.h, src/create_pdf.c, src/logging.c, src/options.h
1. Display unknown in serial number field for loopback device
2. Added device type, USB, SATA, VIRT etc
3. Added duration of wipe in hh:mm:ss
4. Added pseudo random number generator type, twister, isaac etc
5. Added final blanking pass type, none, zeros, ones
6. Added number of rounds
=> PDFGen4 - further work on PDF certificate

src/PDFGen/pdfgen.h, src/create_pdf.c, src/create_pdf.h, src/logging.h
1. Fix @param in pdfgen.h, committed and accepted upstream
2. Added size of disk in bytes
3. When NVME drive show message "Not applicable" for HPA, DCO
4. Highlight status ERASED, FAILED etc with coloured ellipse
5. Added function help for nwipe_log (shows in hints in IDE)
=> PDFGen6 - further work on PDF certificate

src/context.h, src/create_pdf.c, src/logging.c, src/nwipe.c, src/pass.c
1. Added bytes erased including percentage, green if equal to disc size and red if the drive hasn't been fully erased at least once.
2. Added explanation of bytes erased to certificate.
3. Added throughput
=> PDFGen8 - further work on PDF certificate

src/create_pdf.c, src/logging.c, src/pass.c
1. Add information regarding how many pass, sync and verify errors, if any.
=> PDFGen12 - further work on PDF certificate

src/context.h, src/create_pdf.c, src/device.c, src/device.h, src/gui.c, src/hpa_dco.c
1. Reduced font size for data info.
2. Used a define for text point size to make it easier to change size.
3. Started work on function to parse sense data for older versions of hdparm (9.60) that fail to parse the real max sectors correctly. (fixed in 9.65).
4. Miscellaneous changes.
More changes to follow ..
=> PDFGen13 - further work on PDF certificate

src/conf.c, src/conf.h, src/nwipe.c
Basic construction & format of the nwipe.conf file for PDF organisation and customer details
=> PDFGen18 - further work on PDF certificate

src/conf.c, src/create_pdf.c, src/nwipe.c
Completed the code the extracts the organisation and selected customer details from the nwipe.conf configuration file and populates the business and customer details boxes on the PDF report.
=> PDFGen19 Completed data extraction from nwipe.conf

src/gui.c, src/gui.h, src/version.c
Started creating new GUI dialogs. A Configuration dialog and sub dialogs for allowing the user to enter business and customer details. Further dialog windows and code to be added...
=> PDFGen20 Started creating new GUI dialogs.

src/conf.c, src/create_pdf.c, src/gui.c, src/gui.h
Completed all GUI dialog boxes for entering organisational data. Confirmed the data is correctly saved to /etc/nwipe/nwipe.conf and read back for automatic entry into the PDF erasure report. Further work is required to create dialog entry screens for customer details.. to be continued.
=> PDFGen21 Completed all GUI dialog boxes for entering organisational data.

src/conf.c, src/conf.h, src/customers.c, src/version.c
Completed the code that writes the selected customer to nwipe's config file /etc/nwipe/nwipe.conf
=> Completed the code that writes the user selected customer to nwipe's config file

src/customers.c, src/gui.c, src/gui.h, src/version.c
PDFGen24 Created dialogs for adding a customer.
Function to write csv customer entry to /etc/nwipe/customers.csv to follow next.
=> PDFGen24 Created dialogs for adding a customer

src/customers.c, src/customers.h, src/gui.c
Continuation of add a customer entry to the
customers.csv file.
Plus a few corrections to earlier code.
=> PDFGen25 Continuation of add customer csv

src/gui.c, src/gui.h
Created a window where you can edit the systems
date and time. To be completed.
=> PDFGen32 Create Set Date/Time window in GUI

src/gui.c, src/gui.h, src/miscellaneous.c, src/miscellaneous.h
The purpose of this is to read year, month, day, hours minutes and seconds into variables for updating in the GUI prior to writing back to the system.
For systems isolated from the internet this will allow the user to update system date/time from the nwipe GUI rather than having to drop into the command line.
To complete this feature next will be to create the write_system_datetime function.
=> Create function read_system_datetime()

src/gui.c, src/gui.h, src/miscellaneous.c, src/miscellaneous.h
write_system_datetime() and
nwipe_gui_set_system_month()
=> Created further date/time functions.

src/gui.c, src/gui.h
Add functions:
nwipe_gui_set_system_day()
nwipe_gui_set_system_hour()
nwipe_gui_set_system_minute()
=> PDFGen35 Complete Date & time functions

configure.ac, man/nwipe.1, src/context.h, src/create_pdf.c, src/device.c, src/logging.c, src/miscellaneous.c, src/nwipe.c, src/options.c, src/options.h
=> fix for issue #492

src/conf.c, src/device.c
=> bustype detection with smartctl works (again?)

src/gui.c
This was due to incorrectly changing temperature
colour based on historical highest and lowest values.
Also removed some debug nwipe_log code
=> Fix red text on temperature

src/gui.c
Reverted change in wprintw_temperature()
as that was not causing the red temperature
character.
=> Fix_temperature_colour_part2

CHANGELOG.md, configure.ac, man/nwipe.1, src/version.c
Bumped version to 0.35 ready for release, however a further commit will be made to update details of changes to CHANGELOG.md
=> Bump version to 0.35

src/device.c, src/logging.c
=> progress dots added

src/create_pdf.c
Should now read
Page 1 - Erasure Status
Page 2 - Smart Data
Page 3 - Smart Data
and not as previously
Page 1 - Erasure Status
Smart Data - Page 2
Smart Data - Page 3
=> Make smart page titles consistent with page 1

src/create_pdf.c
Updated pdf to recognise XORshiro256 and
lagged Fibonacci PRNGs.
=> Update PDF code with new PRNGs

man/nwipe.1, src/options.c
minor improvement for `--help` info
=> Add missing help for HMG IS5 enhanced

src/prng.c
See https://github.com/martijnvanbrummelen/nwipe/pull/579
=> fix type error on i686 - uint64_t, by @xambroz

.gitignore, README.md, ssd-guide.md
As discussed in issue #590 an update to readme.md and an additional document regarding SSD issues.
=> #590: Documentation: Update Readme.md with information regarding ssd media

src/customers.h, src/isaac_rand/isaac_rand.c, src/isaac_rand/isaac_rand.h
See here.
https://github.com/martijnvanbrummelen/nwipe/pull/658
=> fix: some declaration changes to satisfy gcc 15
