- man/Makefile.am
- man/nwipe.1
- src/nwipe.c
- src/options.c
- src/options.h
Add "--nosignals" option to tell nwipe to ignore signals during a wipe.  Intended for use inside scripts where we don't want users to be able to kill a wipe partway through.
> Add "--nosignals" option to nwipe

- configure.ac
- src/nwipe.h
When there's no pkg-config file for the panel library, the build breaks
if the header is not in /usr/include.
At least in openSUSE, we have /usr/include/ncurses.h and
/usr/include/ncurses/panel.h.
> Fix build when panel header is not in /usr/include

- src/pass.c
The statment free(d), should not be in nwipe_random_pass().
> Pointer d undeclared

- src/device.c
Fixes #50 (Adds ATA/SCSI drive serial numbers to the nwipe GUI).
In addition this patch also adds a new function called trim() that removes leading/trailing white space and left justifies serial number. This is required as some drive manufacturers left justify and others right justify the serial number in the 19 characters, some pad with spaces, some not. trim() creates a standard format that makes the serial number format consistent in the nwipe GUI display.
Serial numbers for USB devices are not displayed and were not previously displayed. Display of serial numbers for USB devices will be released as a separate patch.
This patch also fixes some of the code formatting in device.c, e.g using 3 space tabs where previously there was just spaces proceeding a line of code.
This patch is one …
> Fix non display of serial numbers for ATA/SCSI devices

- src/pass.c
I thought we'd got all the memory leaks, but here's another.
> Memory leak:b in pass.c

- src/logging.c
Closes #60 
More tidying up of the code to clear up warnings, parser errors & cppcheck fails.
This patch fixes the following parser error
```
Implicit declaration of function 'fileno' is invalid in C99 [-Wimplicit-function-declaration]
```
> Fixes implicit declaration of function fileno()

- src/logging.c
In the function nwipe_log(), realloc is called each time a new log line is added. The problem being that a check is not performed on the realloc for NULL to determine whether the realloc actually worked. In the event realloc failed the original pointer would be lost, causing a memory leak. This patch fixes that problem by checking that realloc worked, before assigning the new pointer to log_lines. In the event realloc failed a error is printed to stderr and the function returns.
It also looks like, along with c1 & c2 not being freed, loglines and each malloc log line is also not freed on exit, I need to look further into those cases, however that will be for another pull request...
> Common realloc mistake: nulled but not freed

- src/logging.c
Malloc is used to allocate some memory for storing a log line, however it's return status is not checked prior to use. A consequence of this is that if malloc failed and returned a NULL pointer, the code would not recognise there was a problem and would attempt to write the log text to a NULL pointer resulting in a segmentation fault.
This patch fixes the problem by checking the malloc return status prior to use and if malloc should fail a error message is printed to stderr and the function returns.
> Malloc return status not checked in nwipe_log()

- src/logging.c
- src/logging.h
This patch fixes several issues with the message logging:
1. snprintf() and vsnprintf() functions are not checked for failure (< 0)
2. The return values of snprintf & vsnprintf were assumed to always return the actual number of chars written, which is not the case if the end of the buffer is reached. The return value will exceed the end of the buffer, e.g it returns the number of characters that would have been written if the end of the buffer had not been reached, not the actual number of characters written. Unfortunately the existing code was ignoring that and simply incrementing the pointer into the buffer pushing it past the end of the buffer. This results in a segmentation fault for log messages that are greater than the define MAX_LOG_LINE_CHARS 512.
3. The memory allocation for …
> Fix log message buffer overflow & reduce memory requirements.

- src/logging.c
- src/nwipe.c
- src/nwipe.h
This patch deallocates both the multiple mallocs used for each log message and also the realloc memory that holds the pointers to those multiple log messages.
Confirmed as successfully deallocating the expected number of allocations using valgrind.
This leaves about 400 allocates that are not being deallocated, some of those being c1, c2 allocations. Those will be dealt with in a separate patch.
> De-allocate memory used by the log functions

- src/nwipe.h
Put the function prototype inside the #ifndef/#define/#endif macro to guard against multiple header file inclusion. (and to get rid of the preprocessor warning).
My mistake, this didn't cause an issue, just flags a preprocessor warning.. so now one less warning with the prototype inside the nwipe.h multiple inclusion guard.
> Put Function prototypes inside #ifndef/#define/#endif macro guard

- src/prng.c
The function nwipe_issac_read() has no content, just a return, hence the variables passed via the function call, specifically state, buffer and count are unused. The compiler generates a warning about unused variables in this function.
As I did not want to remove the function as there might be some reason it's there, maybe for some future code, or some other bit of code calls it even though it does nothing, I decided the safest thing to do is (void) the variables in the function to let the compiler know that it's ok. We're aware that they are unused.
This clears 5 warnings, 19 warnings remain out of 24.
> (void) unused variables in func.nwipe_isaac_read()

- src/gui.c
Unused variable 'wy' was causing a 'set but not used' compiler warning.
This patch applies the statement (void) wy; to let the compiler know that 'wy' is purposely unused and to silence the warning.
> (void) unused wy, to silence compiler warning

- src/logging.c
Added va_end( ap ) when various malloc, reallocs might return errors.
> Close va_list 'ap' using (va_end( ap ) on failures

- src/device.c
- src/gui.c
- src/method.c
- src/nwipe.c
- src/pass.c
Removal of the `#include "netinet/in.h"` statements from a number of the source files, did not appear to cause any problems on ubuntu 64 bit, however on ubuntu 32 bit it would cause issues with missing device name, missing drive information related to the GUI display.
This was because the gui.c source should have included ncurses.h, panel.h and most importantly stdint.h Including those headers in gui.c and removing netinet/in.h fixed all the display problems. (netinet/in.h includes stdint.h, hence why netinet/in.h appeared to work).
For other files that included netinet/in.h it was only necessary to replace with stdint.h
Tested on both 32 bit & 64 bit systems.
> Use stdint.h, ncurses.h and panel.h instead of netinet/in.h

- src/nwipe.h
Originally this Fedora workaround was stopping ubuntu 32 bit (16.04LTS) from compiling. Removing the workaround got ubuntu compiling ok, but then without the workaround Fedora 32bit wouldn't compile.
The update to the Fedora workaround fixes this in the define (without changing any other code). So now Fedora 32bit, Ubuntu 32bit and Ubuntu 64bit now all compile without any issues.
> Update Fedora workaround

- src/nwipe.c
This fixes another segfault. The segfault was caused because instead of checking whether the GUI thread was '0' and therefore NOT calling the pthread_cancel function, (because the thread was already cancelled) the if statement was actually checking the pointer to the thread pointer, so trying to cancel with a NULL pointer which causes a segfault.
If the GUI thread was still running, then the segfault wouldn't occur. As there is more than one way the GUI thread terminates in nwipe, I guess that's why this segfault didn't show on some systems and not others, perhaps because of a race condition.
Anyway, now fixed.
Fixes #88
> Fix segfault on immediate CNTRL-C exit, shows in Fedora32 bit

- README
- README.md
This patch adds details of the packages that need to be installed prior to compiling nwipe.
These are basically the things I had to figure out when I first started coding on nwipe on the ubuntu platform. Hopefully it will make things easier for those that want to compile from source. Different distros could be added in the future. For instance I wasn't familiar with the Fedora way of doing things so had to figure that out too.
It also adds some info for developers about how to compile with warnings enabled and switches required if debugging with gdb.
> Update Readme with package requirements

- src/device.c
- src/options.c
- src/options.h
Closes #56
This patch adds a new command line option called '--exclude' or '-e'.
It's purpose is to allow a user to specifiy drives to be ignored by nwipe. By ignore, this means the drive will not be displayed in the GUI or if the autonuke option is specified, autonuke will not wipe the excluded drive/s.
For instance. If your main drive is /dev/sda you can specify on the command line
```
nwipe --exclude=/dev/sda
```
nwipe will not display /dev/sda in the GUI and therefore a user can not inadvertently select the wrong drive for wiping. This feature could be used in an environment where staff are wiping many drives on a system but you don't want the bootable drive wiped. In such a case nwipe could be called from a script such as
```
#!/bin/bash
nwipe --exclude=/dev/sda
```
Up to ten drives …
> Enhancement: Add exclude drive option

- man/nwipe.1
Adds the details of the exclude drive option to the man page:
> Add details of exclude drive option to man page

- README
- README.md
- src/device.c
- src/options.c
Also added some formatting on the code found in the `README.md` file.
@martijnvanbrummelen can you :eyes: please :smiley: 
Also, is there a reason why there's 2 README files?
> Fix typos in README and comments.

- configure.ac
This fixes the following AC warning:
```
configure.ac:6: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
configure.ac:6: https://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
```
As per the deprecation notice, using `AM_INIT_AUTOMAKE` for setting the
version is mostly obsolete because the package and version can be obtained
from Autoconf’s `AC_INIT` macro.
> Fix AutoConf deprecated warning

- src/logging.c
This fix allows nwipe to log an error, specifically the exit code of dmidecode if the exit code
is not 0.
For instance if dmidecode is not installed on a system, then dmidecode reports the following
[2019/11/04 22:12:50] nwipe: info: nwipe_log_sysinfo: dmidecode failed, "dmidecode -s bios-version" exit status = 127
nwipe does not abort on this error but does log the error and continue.
> Fix error reporting when accessing dmidecode.

- src/device.c
- src/gui.c
- src/nwipe.c
Commit "Have nwipe continue with following devices even if one fails:
When using a command such as
>nwipe --verify=last -m zero -r 1 --autonuke --nowait /dev/sda /dev/sdb /dev/sdx /dev/sde /dev/sdf
If one of the drives is not accessible all the remaining drives don't get wiped. Fixed by this commit.
Commit "Fix wip status saying Success when it never even started"
If a drive is enumerated but then fails before the wipe has started, prior to this fix the status in the GUI would say Success. This patch corrects this status message to >>>FAILURE!<<< code -2 under such conditions.
> Fix drive parsing and success status

- .clang-format
- src/options.c
This is a suggestion to add a `clang-format` config file for enforcing the coding style of the project. I formatted a single file to showcase what kind of changes it would perform with the current configuration.
Formatting a single file can be done using the following command
```
clang-format -i -style=file src/options.c
```
Eventually this could be added as a make rule to format all the file of the project.
This is still a work in progress, as I am not sure about a lot of rules defined in the config file. For example, sometimes tabs are used, sometimes spaces. Sometimes there is a space after control statements, sometimes not. Sometimes the consecutive assignments are aligned, sometimes not. It might be a good opportunity to define what styling the maintainers are comfortable reviewing, …
> First clang-format file version.

- src/context.h
- src/nwipe.c
- src/options.c
- src/options.h
- src/pass.c
This fixes [issue 104](https://github.com/martijnvanbrummelen/nwipe/issues/104), [issue 103](https://github.com/martijnvanbrummelen/nwipe/issues/103), and [issue 96](https://github.com/martijnvanbrummelen/nwipe/issues/96).
I changed the unused sync option to enable periodic fdatasyncs during the writes in pass.c.
I stopped nwipe from changing the blocksize, not sure if this should be an option or not.
> Sync changes

- src/options.c
After running clang on options.c the includes were reordered. This caused the compilation to fail with multiple errors.
> Fix order of include files in options.c

- .clang-format
@PartialVolume that will disable the includes reordering.
> Do not sort includes on clang-format

- src/nwipe.c
When aborting a wipe with CNTRL-C, wipe thread cancellation is requested, however the threads won't cancel until the disk cache has been flushed. This p.r. notifies the user via a command line message to please wait as the disk cache is being flushed. How long this takes depends on how long it has been since the last flush, how large the cache is, which is dependant upon how much memory is in the system. In practise this may be from a few seconds to in excess of 30 seconds.
> Add notification of cache flush on CNTRL-C exit

- src/context.h
- src/gui.c
- src/method.c
- src/nwipe.c
- src/pass.c
Closes #95, closes #117 
Symptoms: If you control-C to exit nwipe at the end of a successful
wipe you would get a segmentation fault. If nwipe log data was being
sent to stdout rather than to a log file, then you would not see the
log in the terminal windows after nwipe had exited. This patch fixes
those problems by creating a tri-state wipe flag for each wipe
thread. The main thread after having launched the wipe threads
will wait for ALL wipe flags to report that the wipe routine has
completed and the thread has exited. Only at that time does the
main() routine then proceed with joining the threads and waiting
for the join to confirm the thread has indeed exited. This join
is important as the thread will not actually exit until the OS
has flushed the disk buffers. Currently nwipe does …
> Fix segfault on Control-C, after a successful wipe

- CHANGELOG.md
- man/nwipe.1
- src/options.c
Adds documentation to the `verify` method and fix the help message display (verify option was not in the same block as the other options).
I tried the feature, and it feels weird that all the fields are filled with non-relevant values when using this method:
It could make sense to at least blank these fields when they are not relevant to the current method. @Legogizmo what do you think?
> Add documentation for verify

- src/logging.c
- src/nwipe.c
These warnings pop up when first compiling the project (even when not in dev mode):
```
warning: "_DEFAULT_SOURCE" redefined
```
This makes sure we're only defining those glibc macros if needed.
> Suppress warnings from glibc macros.

- .github/workflows/ci.yml
- README.md
For now the build does not fail with the `gcc` warnings, but that could be changed in the future. Code formatting could also be added at some point.
> Adding GitHub CI build process.

- src/options.c
@PartialVolume as mentioned in the comment, this should never happen, but otherwise we get compiler warnings:
```
options.c:183:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
```
> Exit on invalid long option.

- src/options.c
If using || in the while statement and if 'MAX_DRIVE_PATH_LENGTH' was exceeded the while loop would loop indefinitely.
> warning: logical 'or' of collectively exhaustive tests is always true

- src/gui.c
Update the footers for the commands available in each
screen. Also added the possibility to cancel from the
rounds screen. It was possible to cancel with backspace
from the other screens (method prng etc) but this was not
displayed in the footers. Added the `Ctrl-C` command
to all the footers since this is a global command.
Added the `Left` command to the rounds screen, since it
was implemented but not documented.
Also made sure the Ctrl-C was placed at the end on every
footer.
@PartialVolume please review :eyes:
> Update footers for key commands.

- src/gui.c
During testing a single drive two cores consistently run at close to 100%,
one core at 100% and the other varying between 80-100%. This shouldn't be
the case. Although there would be two threads running, i.e. the gui status
thread and the disk drives wipe thread I would have expected the amount of
CPU required to calculate the on screen stats to be insignificant as they
are only updated once a second.
To reduce the gui stats thread to near zero% while still maintaining the
stats update at one second I inserted an nanosleep interval of 100ms. This
now means that only the one core now shows at 80-100% while all other cores
are close to zero.
> Runtime statistics uses too much CPU

- src/pass.c
#define _POSIX_C_SOURCE 200809L
> Fixes warning "Implicit declaration of function 'fdatasync' is invalid in C99"

- src/logging.c
This patch fixes a segfault that occurs when a logfile is specified.
The segfault occurred on exit of nwipe. It did not affect the wipe
process.
This patch also fixes a related issue, at the end of a wipe some
of the log lines were missing on stdout, this occurred when a log
file was not specified as an option.
closes #134
> Fix segfault & missing log lines

- src/gui.c
- src/logging.c
- src/nwipe.c
- src/nwipe.h
Change code so that there is only one place where the log is flushed on
exit from the ncurses gui. Prior to this patch the flush was done twice
which resulted in duplicated lines and missing lines. The
log_current_element variable was being initialised after the first flush.
This caused subsequent writes to nwipe to write log_lines pointers passed
the end of the pointer array causing memory corruption and resulting in the
occassional segfault on attempts to print the log array.
> Fix missing log lines

- src/method.c
This method is named zero fill everywhere except in the UI, and I feel like zero fill is much more accurate. Will also play well with a future One Fill method, as discussed in https://github.com/martijnvanbrummelen/nwipe/issues/138
> Rename Quick Erase for Zero Fill

- src/gui.c
Rather than delete percentage complete, show it. Because we were hiding
percentage complete we were not aware of inaccuracies in the percentage
calculation that are introduced when you toggle blanking and
verification on various methods.
> Show percentage completed, on completion of wipe.

- src/method.c
Also so that verify and blanking are consistant with other methods.
Fixes percentage calculation for rounds greater than one for the zero fill method.
> Fix zero fill so it works with rounds

- src/context.h
- src/device.c
- src/gui.c
- src/nwipe.c
Also added a `device_label` field to centralize
the creation of the device label. This fixes the
labels for devices without a serial number, and
makes sure we have the same label format everywhere.
@PartialVolume :pray:  :eyes: 
I also changed the format of the device label a bit. I re-introduced the `/dev` prefix in the device name, since I feel it's more explicit to have the full name/path. The size is now just after the name.
> Prefixing device fields with `_device`.

- Makefile.am
@PartialVolume Not sure why I used `diff-index` for that, but now we will see the entire formatting diff in the CI logs.
> Using git-diff --exit-code for diff details.

- CHANGELOG.md
- configure.ac
- man/nwipe.1
- src/version.c
Release 0.27.
Tested on the following distros:
- Debian SID (as of 02/Mar/2020)
- Debian Stable 10.3.0
- Ubuntu 19.10
- KDE Neon 5.18.2 (based on Ubuntu 18.04LTS)
- Fedora 31
> Release 0.27

- configure.ac
- man/nwipe.1
- src/gui.c
- src/gui.h
- src/nwipe.c
- src/version.c
Also fixes an issue where program exits when terminal resized but
only after all the wipes have finished. You can now resize the
terminal, before, during and after the wipes have completed and
the windows are now all correctly updated and sized.
Updated version to 0.28-pre-release
Removed unnecessary zero of gui thread pointer.
Created six new functions in gui.c in order to fix the above problem
and reduce existing duplicated code.
Fixes #195
> Fix window/panel resizing & display when terminal resized by user

- src/gui.c
- src/gui.h
- src/version.c
This fixes screen flicker seen in the following situations:
These apply in full screen mode ONLY: i.e ALT-F2, Shredos etc.
1. When selecting a drive using up/down arrow keys
2. During a wipe the screen flashes at one second intervals.
These apply in a terminal window such as konsole, tmux etc.
1. When resizing the terminal there was a flicker.
All these problems have been fixed.
Most of the causes of the flicker was an excessive use of wrefresh() which calls
the wnoutrefresh() and doupdate() functions. This can cause flickering when a
number of calls to wrefresh happen at the same time. It is more appropriate to
replace the wrefresh() with wnoutrefresh(), then at an appropriate time call
doupate() just once. The result is that before doupdate() would have been
called multiple times and …
> Fix flicker

- src/logging.c
@martijnvanbrummelen Use sizeof to determine the size of the character array that we construct the dmidecode command in.
This is a better way to determine the array size as it's determined by the compiler. It also means that if the dmidecode keyword is added to the destination array size is automatically adjusted by the compiler.
> Fix overflow warning

- src/gui.c
- src/nwipe.h
Fix 1 second delay on screen update when terminal is resized.
During a wipe there is a approximately 1 second delay between  resizing the window and the screen fully updating. This has been corrected so screen updates and as a consequence key response is
faster. This makes the GUI interface feel smoother and more responsive with windows updating much quicker.
> Slow main window refresh during wipe after terminal resize

- src/gui.c
On completion of a device wipe, the throughput was continuing
to be calculated for a completed wipe which resulted in the
throughput for that particular device to gradually drop over time
to zero if other drives were still
This has now been corrected. Throughput calculation for a given
device is stopped when the particular device has completed its wipe.
> Fix individual device throughput.

- man/nwipe.1
- src/nwipe.c
- src/options.c
- src/options.h
Add verbose option -v, --verbose
Only display thread cancellation info messages, excluding error
messages, only when verbose option is selected.
This helps to keep the log a bit cleaner especially when wiping many
drives simultaneously.
> Add verbose option

- src/device.c
- src/logging.c
- src/method.c
- src/nwipe.c
1. Keep nwipe_log notices succinct and below 80 chars in length including
timestamp. This is especially relevant for 80x30 terminal use such
as ALT-F2 etc or Shredos without losing any information.
2. Add [SUCCESS] to blanked & verified messages to make them stand out for quicker checking.
3. Combine the three sector size, block size, device size into a single message for each device.
These changes are most relevant when wiping many drives simultaneously.
**Example after changes**
> [2020/03/13 16:44:34] notice: Found /dev/loop13, Loopback device, 1074MB, S/N=
[2020/03/13 16:44:34] notice: Found /dev/loop14, Loopback device, 1074MB, S/N=
[2020/03/13 16:44:34] notice: Found /dev/loop15, Loopback device, 1074MB, S/N=
[2020/03/13 16:44:34] notice: Found /dev/loop16, Loopback device, 524MB, …
> Reduce unnecessary lines in log while retaining info

- CHANGELOG.md
- src/context.h
- src/gui.c
- src/gui.h
- src/nwipe.c
Add a spinner to the GUI for each drive being wiped.
When nwipe is syncing the percentage completion pauses,
having a spinner gives a clear indication that the wipe
is still running. Each devices spinner disappears on completion
of a given devices wipe.
> Add a spinner to the GUI for each drive

- CHANGELOG.md
- src/context.h
- src/logging.c
- src/logging.h
- src/method.c
- src/nwipe.c
- src/nwipe.h
- src/prng.c
Add a summary table to the log that shows each drives status
i.e. erased or failed, throughput, duration of wipe, model,
serial no etc. In particular it benefits those that wipe many
drives simultaneously in rack servers. At a glance any failed
drives can be seen without having to browse back through the
log. Especially useful in --nogui mode, but also useful in GUI
mode.
Single drive example (15 drive example further down)
```
[2020/03/18 17:59:56] notice: Device /dev/sda excluded as per command line optio
[2020/03/18 17:59:56] notice: Device /dev/sdb excluded as per command line optio
[2020/03/18 17:59:56] notice: Found /dev/sdc, ATA WDC WD1600AAJS-2, 160GB, S/N=W
[2020/03/18 17:59:56] notice: Device /dev/mapper/cryptswap1 excluded as per comm
[2020/03/18 17:59:56] info: Automatically …
```
> Add a summary table to the log that shows each drives status

- src/logging.c
- src/nwipe.c
If the system is shutdown while nwipe is still
wiping, the duration calculation would be
incorrect. This patch fixes that problem, so for
instance if a UPS signals the system running nwipe to
shutdown, nwipe typically traps that signal and
exits in an orderly manner. The log summary
is generated showing the wipe was aborted and
the wipe duration shows a valid value i.e the
elapsed time since the start of the wipe.
**Example of nwipe summary table after a shutdown is initiated mid wipe.** 
```
[2020/03/19 15:42:09] notice: Device /dev/sda excluded as per command line option -e
[2020/03/19 15:42:09] notice: Device /dev/sdb excluded as per command line option -e
[2020/03/19 15:42:09] notice: Found /dev/sdc, ATA WDC WD1600AAJS-2, 160GB, S/N=WD-WMAV2FS49552
[2020/03/19 15:42:09] notice: Device …
```
> Fix incorrect summary duration during shutdown

- CHANGELOG.md
- src/gui.c
- src/logging.c
Fix throughput so it shows the average throughput
calculated from the start of the wipe.
Because we currently use cached access to the disks
initially for a few seconds or minute the throughput looks high
as nwipes writes are cached in memory before being written to disc.
When we change to a non cached or nwipe buffered model the
throughput will reflect a throughput that is actual
disc throughput.
Using an averaged throughput means that when the wipe finishes it will show
a higher value than the previous calculation but this new calculation is the
actual averaged speed of the wipe and reflects a value that is closer to what
you would expect a given drive to exhibit.
For instance a 160GB WD1600AAJS using Dod-S, B+VL, using the old
calculation would finish with a throughput of 48MB/s, using …
> Fix throughput so it shows the average throughput

- src/gui.c
I don't know if it's just me, but I'm not keen on the
way the status line length changes every few seconds
depending on whether nwipe is syncing or not. So
while still retaining the syncing message I think
it looks better if when not syncing, [syncing] is
replaced with [-------]. This keeps the status line
length pretty much constant and I find it easier on
my eyes.
> Make the [syncing] a bit easier on the eyes

- src/logging.c
In Debian Sid dmidecode is not found as /sbin is not
searched when nwipe only specifies 'dmidecode', so
if it fails then it will next try /sbin/dmidecode
which is where it's normally located if it's installed.
In ubuntu etc, the sudo environment is setup so /sbin
is automatically searched.
> Check for dmidecode in /sbin

- CHANGELOG.md
- src/context.h
- src/device.c
- src/device.h
Add serial number support for USB devices for USB
to IDE/SATA adapters. Note this will only work
with USB IDE/SATA adapters that support ATA pass
through. See #149 for further details of
supported devices.
This patch requires readlink and smartmontools (smartctl)
to be installed. If not installed the serial number for
supported USB hardware will be missing.
Chipsets that support this include:
ASMedia, Initio, Oxford, newer JMicron-JM20329, JM20335-39, Prolific PL2507/3507 PL2571/2771/2773/2775 ,Sunplus SPIF215/6, SPIF225/6.
Jmicron, Prolific and Sunplus supports fully ATA pass-through.
Further information can be found here:
https://www.smartmontools.org/wiki/USB
In addition, the device type, i.e USB or ATA is now shown on the selection
and wipe windows.
Closes #149
> Add serial number support for USB devices

- src/device.c
If any drive doesn't have a serial number it's
serial number field was populated with the previous
drives serial number.
This is fixed by this patch.
> Fix duplicated serial number

- src/context.h
- src/device.c
- src/device.h
- src/logging.c
- src/logging.h
I've always wondered, when you first view all the drives, why drives above 999GB appeared in their GB nomenclature instead of TB. For instance a 2TB drive would appear as 2000GB. Unlike other places in nwipe that does a proper job of describing capacity just this one location in the program was wrong.
This information was obtained by a call to a function in libparted. Maybe when libparted was written there was no such thing as a TByte drive ?? Who knows, so anyway it was far easier to use nwipes build in function called 'determine_C_B_nomenclature()' This provides us with the correct nomenclature that is a fixed number of digits (three) and prefixed with spaces so the length is always the same. In the GUI this gives a nice list when viewing multiple drives that appears in neat columns. …
> Fix incorrect disk capacity nomenclature.

- CHANGELOG.md
- man/nwipe.1
- src/device.c
- src/nwipe.c
- src/options.c
- src/options.h
If you use the option --nousb, all USB devices will be ignored.
They won't show up in the GUI and they won't be wiped if you use
the --nogui --autonuke command. They will even be ignored if you
specifically name them on the command line.
Closes #81
> Add --nousb option.

- src/gui.c
- src/nwipe.c
Fix individual drive throughput running after a wipe has finished.
This problem was not seen when wiping multiple drives
of the same size as they all ended at the same time.
Also not seen when wiping  a single drive, but if you
wiped multiple drives of different sizes where the
drive wipes ended at different times then you could
see the throughput being calculated as steadily dropping
for a drive that had completed it's wipe.
Also fixed overall throughput. When all wipes had completed
overall throughput showed the throughput of the last drive
that finished. It should show 0 B/s as all wiping had
ceased. In the log table you will see individual drive
throughput and overall throughput which is the sum of
all the drives throughputs.
> Fix individual drive throughput running after a wipe has finished

- src/gui.c
When wiping a drive a status message is displayed
that show [writing] or [syncing] or [verifying] or
[blanking] etc. Previously there were two bracketed
fields, [syncing] occupied one field and all the others
occupied the other field.
To conserve screen space they all occupy the same
bracketed field.
The bracketed field is also now a fixed length of
9 characters padded with spaces as necessary to maintain
column alignment when wiping multiple drives simultaneously.
> Combine [writing][blanking] fields

- src/gui.c
For drives that are wiping the percentage
completion is displayed. To retain column
alignment when wiping multiple drives, the
percentage values from 0.01% to 9.99% are
displayed with a leading space, i.e
[ 9.99%, then 10.00% to 99.99% is displayed
as, i.e [10.01%, etc..
> Make percentage width fixed.

- src/gui.c
When a drive fails display the failure message with red text on a white background.
This makes it more visually obvious a drive failure has occurred and is especially important when you are many disk drives simultaneously. One failure message amongst twenty eight success messages, especially when all the text is white on blue can sometimes be overlooked.
With this patch the failure message stands out.
Closes #245 
```
[2020/03/30 19:59:11] notice: Opened entropy source '/dev/urandom'.
[2020/03/30 19:59:52] notice: /dev/sdf, sect/blk/dev 512/4096/359923712
[2020/03/30 19:59:52] notice: /dev/sdg has serial number (no ATA pass thru)
[2020/03/30 19:59:52] notice: /dev/sdg, sect/blk/dev 512/4096/-1578016768
[2020/03/30 19:59:52] notice: Invoking method 'Zero Fill' on /dev/sdf
[2020/03/30 …
```
> Visually enhance failure messages

- CHANGELOG.md
- src/context.h
- src/device.c
Added NVME and VIRT to device type table.
VIRT are virtual devices such as loop devices
created with losetup.
NVME for solid state storage devices.
Due to the longer device names used for NVME, I will
need to do some work on the device name in the selection
window so column alignment is maintained.
> Add NVME & VIRT to device types.

- src/gui.c
This was a very obscure segmentation fault I stumbled across while testing the drive selection window. I confirmed it exists in all versions at least going back prior to 0.24 and maybe a lot earlier.
It was a very tricky bug to track down as you had to do some very specific things to cause it to occur. Probably most people would not have seen it, however for those that did, this was what you needed to do to trigger it.
1. First you had to be wiping more than one drive.
2. Then you needed to scroll down to the bottom drive in the list.
3. You then needed to minimise the vertical height of the terminal so you could no longer see the selected drive.
4. Then you needed to expand the vertical height of the terminal. This last step would trigger a segmentation fault and crash nwipe.
So, the …
> Fix obscure segfault when resizing terminal

- src/device.c
If a USB device generated a particular error code from smartmontools, the --nousb option incorrectly did not exclude it from the enumerated drives.
This has now been corrected.
> Fix --nousb missing a drive

- README.md
Recompiled ShredOS with support for Smartmontools, C++ V7.x support. Nwipe in this version of ShredOS, now supports the display of serial numbers for USB bridges that have chipsets that support ATA pass through functionality.
> Update README.md with latest ShredOS details

- src/logging.c
Previously if a drive failed during a multiple drive wipe and the user decided to abort nwipe, for instance, to remove the drive and start over, the user would use CONTROl-C to abort.
This would be reflected in the summary table as ALL drives having been aborted including the drive that failed. However, it makes more sense for a failed drive to be marked as failed in the summary table even though the user had aborted the wipe.
This patch fixes that, so that if a drive failed it reflects that drives status as failed in the summary table even if the user had aborted the wipe.
> Fix summary table message precedence

- src/device.c
- src/device.h
We already determine the bus type, ATA, USB, NVME, VIRT (loop) etc and display the bus type on the GUI. libparted prefixes the model number with ATA which we don't need, especially as we try to keep the drive display length to a maximum of 80 characters.
> Remove redundant ATA prefix from the model number.

- src/nwipe.c
Fix a minor error in the reporting of the discs total number of blocks. This only affects reporting to the log file and does not affect the programs operation.
> Fix minor error in reporting block size in log

- CHANGELOG.md
- src/gui.c
I have come across a new user that couldn't start a wipe, until it was pointed out that to start a wipe you needed to type shift S. While this is often true, shift S doesn't start a wipe if you have caps lock on. To be precise you need to type a capital S. Confusing to a new user because if they have been told to type shift S but their caps lock is on, then nothing happens. Also how would you know you are supposed to type a capital S when the key info puts all keys in caps.
The fix for this is to trap the lower case s and then print a message on the status line that says "Use capital S to start a wipe". This message could remain on the status line for 3 seconds then revert back to the standard key info.
The use of capital S is to try to reduce the likelihood of an accidental wipe you …
> Warn user if they press 's' instead of 'S'

- CHANGELOG.md
- src/gui.c
- src/version.c
If a user attempts to start a wipe but hasn't yet selected any drives for wiping, a warning message will now appear for a few seconds suggesting they select a drive.
Prior to this patch, if you tried to start a wipe without selecting a drive, nwipe would immediately display a message saying the wipe was complete and press enter to exit. You had no choice but to exit and restart nwipe.
> Warn user if no drives are selected, when attempting to start a wipe

- src/gui.c
- src/version.c
To select or deselect all drives for wiping you can now type ctrl a.
Useful for users that are wiping many drives simultaneously.
Closes #266
> Add ctrl a to select/deselect wipe for ALL drives.

- src/nwipe.c
- src/version.c
If you do a ctrl c to exit nwipe before you have even started a wipe, it will be reported in the logs that there are fatal or non fatal errors. This is incorrect as no wipe has even been started.
This error is only relevant to when using ctrl c before a wipe has started and not after a wipe has started.
Basically the variables that hold the errors are in an indeterminate state before wiping begins and in the case of a user abort we mistakenly checked those values and reported. They should only be used after a thread has completed or failed when their values are then valid.
Now if you exit nwipe before any wiping started there are no fatal/non fatal errors reported.
> Fix_error_reporting_on_ctrl_C before wipe starts

- src/gui.c
Prior to this patch if the 'S' key was held down, the keyboard would be unresponsive for x seconds.
Where x = number of S keystrokes x 3.
Now keys are delayed for no longer than 3 seconds, while the warning message is displayed, long enough for the user to read the warning message.
> Fix nwipes behaviour with repeated S key

- src/nwipe.c
When nwipe is run as user without root privileges, the message displayed will be "storage devices not found", which is true but possibly misleading to a new user. The message was amended to include a statement mentioning that nwipe needs to be run as root, sudo or su etc.
> Add sudo/su help message

- src/logging.c
Right justify log labels in order to maintain column alignment
> Right justify log labels.

- src/logging.c
- src/logging.h
- src/nwipe.c
This commit adds nwipes banner version number and OS info derived from /proc/version to the nwipe log. This information may be useful when a user has an issue and submits a log file.
> Added /proc/version info to log

- src/logging.c
- src/nwipe.c
- src/nwipe.h
- src/version.c
1. Prior to this fix, if a user aborted a multi drive using control-C,
and if some of the drives had completed their wipe either
successfully or with a I/O failures, the summary log would say
UABORTED for all drives. UABORTED is acceptable status for drives that
hadn't completed their wipe but for drives that had completed the wipe,
the summary table should have gave either a ERASED or FAILED status
message. This fix corrects the summary status when using control-c to
abort a multi drive wipe where some drives have completed and some have
not.
2. If I wipe was selected but not started and then the user used
control-C to abort nwipe, the summary table would possibly
intermittently be displayed showing the last drive wiped. The correct
behaviour is that no summary table is displayed if the …
> Fixes to summary table & fix final status message

- src/gui.c
... and reduce confusion about lowercase and uppercase option. All options are now defaulting to show as lowercase in the GUI except Start which can only be invoked with SHIFT S to prevent accidental start of wipe. Unless someone enjoys pressing additionally SHIFT for B and R and V and all the other options I'd propose it might be time to remove unneeded code for this :)
> Update gui.c - Add CTRL+A

- src/gui.c
This bug only occurs when you resize the terminal while
on the drive selection screen, then switch to method, rounds
or blanking. To the right of the message the text background
is now blue and not white and random box characters appear.
To me it seems to be a bug not in nwipe but in curses, however
placing double quotes around the message fixes the problem. I
also found that the contents of the message appeared to trigger
the problem, possibly the '=' symbol, however the fact that
the main selection text does not require the quotes is most odd.
Still, this simple fix seems to get rid of the problem.
Fixes #305
> Fixes footer bar corruption to the right of the message

- src/nwipe.c
- src/nwipe.h
I just tried to build `nwipe` on:
```bash
avj@platypus ~/clones/nwipe$ lsb_release -a
LSB Version:	core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-x86_64:core-3.2-x86_64:core-4.0-x86_64:desktop-4.0.fake-amd64:desktop-4.0.fake-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0.fake-amd64:graphics-4.0.fake-noarch
Distributor ID:	openSUSE
Description:	openSUSE Tumbleweed
Release:	20210223
Codename:	n/a
```
with:
```bash
avj@platypus ~/clones/nwipe$ gcc --version
gcc (SUSE Linux) 10.2.1 20201202 [revision e563687cf9d3d1278f45aaebd03e0f66531076c9]
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR …
```
> Correcting multiple definition of 'global_wipe_status'

- src/nwipe.c
The shutdown command that nwipe currently uses is
"shutdown -P +1 "Broadcast shutdown message".
While the above command works works fine on Ubuntu 18.04 LTS it
does not work on the version of shutdown used in buildroot, failing
with the error:
"shutdown -H and -P flags can only be used along with -h flag"
Luckily there is a shutdown command with options that work correctly
on both buildroot (ShredOS) and Ubuntu 18.04 LTS, this is
shutdown -Ph +1 "Broadcast shutdown message". i.e. the option -h has been added.
> Fix shutdown on buildroot based distros

- src/logging.c
- src/method.c
- src/nwipe.c
- src/version.c
1. The log reported verification errors while also
showing an entry in the log that said "[SUCCESS] Blanked /dev/...".
The blanked device message now shows [FAILURE] /dev/... may not be blanked"
if any verification errors are detected for a specific drive.
2. If a verification error occurred, the error would be correctly
shown in the GUI and in the logs but the summary table drive status
would show 'ERASED' not 'FAILED'. Now corrected so that the tables
drive status field shows 'FAILED' if any verification error is detected.
Prior to this it was marking the status as 'FAILED' only if the O.S
detected write errors. In practise most drive errors are detected
by the write I/O process on syncing but this will now detect errors not
recognised by the O.S. and found by the verification process. …
> Fixes contradictory log messages.

- src/pass.c
- src/version.c
Additional log messages are produced and a failed prng
causes a wipe failure. The buffer that outputs prng data
to the disk is now initialised with zeros (calloc rather than malloc)
to avoid uninitialised memory leakage to the disk in the event of some
unforeseen bug. This initialised buffer is also required for the check
process.
Why do this check? At a future date more prng methods may be added. This
is a very basic check that they produce some output although the output
is not verified in terms of it's randomness. This check was also
implemented to show an existing bug in the Isaac implementation in nwipe.
See the example log below that shows a failed prng. This would be caused
by a bug in the prng implementation. See the last few messages after
pass 3/3 starts. 3/3 in DoD short is the …
> Check that the prng produces output.

- src/isaac_rand/isaac_rand.h
- src/prng.c
- src/prng.h
- src/version.c
Since at least 2013 (the initial nwipe commit),
isaac has never functioned. When the issac prng
was selected in the GUI, nwipe used the mersenne
twister prng instead. Not that you would ever
have known, as there were no log entries saying which
prng was being actively used.
However, I don't believe this was just an nwipe
issue, looking at the code for DBAN's dwipe the
same function nwipe_isaac_read( NWIPE_PRNG_READ_SIGNATURE )
exists as it does in nwipe. In both cases the function
has no code that actually does anything.
This patch populates this function and brings isaac
back to life !
This bug was also responsible for verification errors
when the option prng=isaac was used on the command
line. Worse still, if you used prng=isaac on the
command line then wiped using method=prng, no …
> Fix non functional isaac prng

- src/nwipe.c
This patch fixes the issue where irrespective
of whether the user selects mersenne or isaac
in the GUI, mersenne is always used without the
user being aware mersenne was being used instead
of isaac.
> Fix the prng GUI selection

- src/method.c
- src/prng.c
- src/version.c
Although the blanking pass verification is
completed correctly the GUI status message
did not show the status as 'Verifying', the
status message continued to say blanking.
This patch fixes the GUI message so if
verification and blanking pass are enabled,
then when blanking is complete and verification
starts the drive status message changes from
'blanking' to 'Verifying'.
> Fix blanking pass verification status message

- src/logging.c
Closes #283 
In addition to the existing drive status log table, a pass & verification error log table has been created that will appear in nwipe's log.
> Add pass and verification summary table to log

- src/gui.c
- src/method.c
- src/version.c
1. Allows zero fill to be verified when blanking off. Prior to this if you wanted to verify a zero pass, blanking had to be on. This meant a zero pass, then a blanking pass then a verify, effectively two zero passes and a verify. This is now fixed so you can now do a zero pass with verification without a blanking pass. This knocks a third off the wipe time of a zero fill with verification !. This also means all other methods can have either all their passes  or just the last pass verified, whether static or random, without blanking being enabled. Optionally a blanking pass with or without verification can be selected except for the Ops2 method which requires a mandatory random pass.
2. OPS2 method requires the last pass to be random, the GUI now disables the use of the blanking option for …
> Allow Last Pass Verify to work without requiring final blanking (zero) pass.

- src/gui.c
When highlighting the verify ones option the first two
digits of DoD 5220 .20-M disappear. This patch fixes that
issue.
> Fix slight screen corruption on 80 column display

- src/context.h
- src/device.c
- src/version.c
For some controllers/drivers the readlink method of
obtaining the bus type for GUI display does not work.
If we haven't already resolved the bus type, we then
also check smartctl for the transport protocol
for SAS.
> Add SAS to GUI.

- src/pass.c
The `it's` → `its` typo is not detected by codespell. Both are valid.
A higher level analysis would be required to detect that kind of typo.
> Typo not found by codespell

- .codespellrc
It is much easier to setup [codespell](https://github.com/codespell-project/codespell) in Python projects, as the configuration can be added to the standard Python file `setup.cfg`. Here, we have to add the new `.codespellrc` file.
> Add a .codespellrc file to run codespell

- src/device.c
For some controllers/drivers the readlink method of
obtaining the bus type for GUI display does not work.
If we haven't already resolved the bus type, we then
also check smartctl for the transport protocol
for SATA.
> Check smartctl for unresolved bus types SATA

- src/Makefile.am
- src/context.h
- src/device.h
- src/gui.c
- src/gui.h
- src/logging.c
- src/logging.h
- src/nwipe.c
- src/prng.h
- src/temperature.c
- src/temperature.h
| Color/status of temperature readout | Meaning |
| ----- | ------ |
| White | Within operating temperature |
| Red | Maximum continuous operating temperature reached |
| Red Flashing | Critical temperature reached, damage may occur |
| Black | Minimum continuous operating temperature reached |
| Black flashing | Minimum critical temperature reached, damage may occur |
Demo video showing how temperature display changes based on min,max,upper/lower critical limits as supplied by the drive.
https://user-images.githubusercontent.com/22084881/141209512-97bce553-00d0-46fd-9da3-bcebf0cbd93d.mp4
> Add drive temperature monitoring

- src/device.c
- src/gui.c
- src/gui.h
- src/version.c
Added temperature to drive selection window.
Also removed 1. 2. etc from drive selection line
to reduce the line length. Also removed the
space between > and [, ie "> [wipe]" becomes
">[wipe]" These changes remove 3 characters
and help to reduce the affect of the additional
temperature field [30C] which add 5 characters.
Therefore the line length overall, increased by
two characters.
This helps to reduce line wrapping on 80
character terminals when the drive model length
exceeds 24 characters.
> Added temperature to drive selection window

- src/gui.c
- src/version.c
In both selection and wipe status windows I
moved the temperature readout to the right
of the disk size column.
Also in the wipe status window, by moving to
the right of the disk size column the
temperature is no longer on the same line as
the disk pass progress. This reduces the line
length as I found that in tests if you had
many verification errors the temperature
being on the end of the line would disappear
of the right of the screen
.
> Moved the temperature readout

- src/context.h
- src/device.c
- src/device.h
- src/gui.c
- src/logging.c
- src/temperature.c
This fixes column alignment issues in the gui
with nvme drives i.e. nvme0n1 etc. If the drive
name including path exceeds 8 characters the
/dev/ is removed and prefixed with spaces to
a total max length of 8 characters.
> Remove /dev/ from gui for long filenames

- man/nwipe.1
- src/device.c
- src/nwipe.c
- src/options.c
- src/options.h
- src/version.c
Anonymize the serial numbers in the gui, the
log and the summary table.
If a serial number was obtained from the device,
it is replaced with "XXXXXXXXXXXXXXX".
If the serial number could not be obtained from the
device, it's replaced with "???????????????".
```
sudo ./nwipe -v -q /dev/loop39 /dev/loop40
[2021/11/15 18:24:12]    info: nwipe 0.32.006
[2021/11/15 18:24:12]    info: Linux version 5.11.0-38-generic (buildd@lgw01-am
d64-041) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.
3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #42
~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 202
1
[2021/11/15 18:24:12]   debug: Readlink: ../devices/virtual/block/loop39 
[2021/11/15 18:24:12]   debug: smartctl: smartctl 7.1 2019-12-30 r5022 [x86_64-linux-5.11.0-38-generic] (local build) 
[2021/11/15 18:24:12] …
```
> Add -q --quiet option - anonymize serial numbers

- src/logging.c
Anonymize SMBIOS/DMI data if -q --quiet specified by the user.
```
sudo ./nwipe -q
[2021/11/15 21:49:54]    info: nwipe 0.32.006
[2021/11/15 21:49:54]    info: Linux version 5.11.0-38-generic (buildd@lgw01-am
d64-041) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.
3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #42
~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 202
1
[2021/11/15 21:49:54]  notice: Found /dev/sda,  ATA, SanDisk SDSSDH3, 500 GB, S/N=XXXXXXXXXXXXXXX
[2021/11/15 21:49:54]  notice: Found /dev/sdb,  ATA, ST2000LX001-1RG1,   2 TB, S/N=XXXXXXXXXXXXXXX
[2021/11/15 21:49:54]  notice: Found /dev/sdc,  USB, ST1000DM 010-2EP102,   1 TB, S/N=XXXXXXXXXXXXXXX
[2021/11/15 21:49:54]  notice: Found /dev/sdd,  USB, WDC WD20 EURS-63SPKY0,   2 TB, S/N=XXXXXXXXXXXXXXX
[2021/11/15 21:49:54]    info: …
```
> Anonymize SMBIOS/DMI data if -q --quiet specified

- src/logging.c
- src/method.c
- src/nwipe.c
If you used control-c during a wipe,
the summary table would report FAILED
rather than UABORTED, even though no
errors had occured and no errors were
reported in the error summary table.
The correct message on control-c abort
should be UABORTED if no errors on that
drive had so far been detected or FAILED
if errors had been detected.
nwipe reported correctly when letting
the wipe continue to it's natural completion.
This patch fixes that issue.
> Fix summary table - Control-C

- src/gui.c
- src/version.c
When many verification or pass errors are detected
the status line can wrap on a 80 column display.
This patch makes the error message more succinct
which will free up about 10 characters & prevents
the line wrapping.
> Make verify & pass error succinct

- src/gui.c
- src/version.c
If a faulty drive fails mid wipe and it's
throughput drops until eventually reaching
zero. The ETA calculation grows to an enormously
high value.
This patch prevents the ETA being calculated if
the throughput for a given drive drops below
100,000 bytes per second. In this way we can still
see that something is wrong because the ETA is much
higher than normal but prevents the sort of calculation
that looks like this ! 90867213:29:12 i.e ..
90,867,213 hours, 29 minutes and 12 seconds, or put
another way, 3,786,133 days or 10,372 years.
Fixes #372
> Fixes ETA under fault condition

- src/temperature.c
Patch #1 (first check) @Firminator If you could check whether the NVME temperatures now show up. If they don't, could you anonymize/verbose the log (nwipe -v -q) and paste the results.. Thanks
> Add temperature support to NVME drives

- src/gui.c
In the drive selection window when you
select a drive, the drive is identified
as selected for wiping with the [wipe]
label, however if you then select a
verify only method such as 'verify with
ones' or 'verify with zeros' it still
says [wipe] which is technically a
contradiction.
This patch changes the [wipe] to a
[vrfy] when a verify only method is
selected. If a method is selected
that writes data to the disc then the
label is displayed as [wipe]
https://user-images.githubusercontent.com/22084881/142231125-7c7945d0-8aae-4c7e-8cc0-0bdea9d336f5.mp4
> Distinguish between a wipe & verify

- src/gui.c
- src/version.c
When selecting -q or --quiet as an nwipe
option, append " (ANONYMIZED)" to the nwipe
banner.
> Make it clear we are in anonymized mode

- src/temperature.c
- src/version.c
For sdX devices we look in
/sys/class/hwmon/hwmonX/block for the device
name.
However, for nvme we access the device name
by looking in ..
/sys/class/hwmon/hwmonX/device/nvme/nvme0
nvme0n1
Multiple nvme drives/controllers will need
to be tested.
> Update nvme temperatures.

- src/temperature.c
- src/version.c
Add /sys/class/hwmon/hwmonX/device/ to the list
of directories to search for a given device.
Some nvme devices/controllers put the device name
in /sys/class/hwmon/hwmonX/device/ rather than
/sys/class/hwmon/hwmonX/device/nvme/nvme0/
Update debug messaging.
> Update temperature for some nvme devices

- src/nwipe.c
- src/version.c
Causing incorrect sect/block/device size to be
printed in nwipe_log but only for 32 bit builds.
> Fix 2nd occurrence of incorrect format specifier.

- src/nwipe.c
Particularly relevant to Debian which when logged in as root
doesn't put /sbin in the $PATH environment setting.
This might have caused temperatures to not be available on Debian
systems, but not necessarily on distros based on Debian like
Ubuntu which would have worked ok.
Fixes #389
> Check multiple paths for modprobe

- src/nwipe.c
- src/version.c
If pthread_join failed, nwipe would report an error
but would also report that the thread had been
cancelled. This has been corrected so that only
the error message is displayed in a fault condition.
> Improve GUI thread cancellation messaging

- src/device.c
- src/version.c
This was caused by inconsistent labeling of the
serial number by smartctl. In a majority of cases
smartctl would output serial number data using
the label "Serial Number:" however on a SAS
drive we found that smartctl output the label
as "Serial number:" i.e. differs with a lower
case 'n'. Unfortunately we were doing a case
sensitive search for "Serial Number" so the result
being the serial number was not found.
This patch converts both strings in the search
to lower case before searching.
In addition a new field was added to the
anonymize list, "logical unit id:" so when the
-q option is used "serial number", "lu wwn device id:"
and "logical unit id:" are all now anonymized in the
smartctl debug data.
Fixes #384
> Fix missing serial number on SAS drive

- src/Makefile.am
- src/gui.c
- src/isaac_rand/isaac64.c
- src/isaac_rand/isaac64.h
- src/isaac_rand/isaac_rand.h
- src/isaac_rand/isaac_standard.h
- src/options.c
- src/prng.c
- src/prng.h
Use RANDIZL=8 as recommended by ISAAC author.
Fixed possible buffer overflow in nwipe_isaac_read().
Slight performance improvement.
> Added ISAAC-64 PRNG for 64-bit systems.

- src/method.c
https://www.cs.auckland.ac.nz/~pgut001/pubs/secure_del.html
>The basic disk eraser can be improved slightly by **adding random passes before and after** the erase process, and by performing the **deterministic passes in random order** to make it more difficult to guess which of the known data passes were made at which point.
>The **deterministic patterns between** the random writes are permuted before the write is performed, ...
> Random passes in the Gutmann method should not be rearranged.

- src/nwipe.c
- src/version.c
If the drive becomes non responsive during the wipe, the MB/s will
slowly drop towards 0MB/s and will display a FAILURE -1 error. The logs
will display errors and nwipe's return status will be non zero, however
the summary table may display erased rather than FAILURE, this is because
the wipe thread exited prematurely without setting the pass error.
This fixes the error by checking the context's result status, i.e non zero
on failure and if pass equals zero it makes pass equal to one. This is
then picked up by the summary table log code which then marks the status
correctly as FAILURE in the summary table.
> Fix obscure incorrect summary table status

- man/nwipe.1
- src/options.c
Reverts martijnvanbrummelen/nwipe#402
> Revert "Revert "Isaac64, update options, help and man page""

- src/gui.c
- src/version.c
This patch fixes a minor display issue that occurs when
a user aborts a wipe before a wipe has started. It only occurs
if the user had selected one or more drives for wipe and then
aborted before starting the wipe. The spurious message only
occurs in a virtual terminal, i.e. /dev/tty1, /dev/tty2, /dev/console
It does not occur in terminal applications such as konsole, xterm,
terminator etc.
The spurious message that appears in the main window, states that
"/dev/sdxyz 100% complete" along with garbage values in the statistics
window. The message appears for a fraction of a second before being
replaced with the textual log information that correctly states that
the user aborted and no wipe was started.
Basically the gui status information update function tries to update
the data when the …
> Fix spurious message on abort before wipe.

- src/gui.c
- src/version.c
This fixes a problem where the drive temperature is not updated
automatically in the drive selection window only. The temperature
is however updated every correctly every 60 seconds during a wipe in
the wipe status window.
This bug would probably never be noticed by most people as usually the
drive temperature changes slowly and only rises once a wipe has started.
The only time I imagine it would have been noticed would have been if
the drive temperature was already high and you were trying to reduce the
temperature by cooling before starting a wipe.
This has now been corrected so that the temperature in the drive
selection window is updated every 60 seconds.
> Fix temperature update in drive selection window

- src/gui.c
- src/gui.h
- src/version.c
when Konsole terminal exited while nwipe is sitting at the
drive selection screen.
To avoid 100% CPU usage, check for a runaway condition caused by the
function "keystroke = getch() that immediately returns an error
condition. We check for an error condition because getch() returns a
ERR value when the timeout value "timeout( 250 );" expires as well as
when a real error occurs. We can't differentiate from normal operation
and a failure of the getch function to block for the specified period
of timeout. So here we check the while loop hasn't exceeded the number
of expected iterations per second ie. a timeout(250) block value of
250ms means we should not see any more than (1000/250) = 4 iterations.
We double this to 8 to allow a little tolerance. Why is this necessary?
It's been found that …
> Fixes a 100% CPU usage on Konsole based terminal

- src/gui.c
- src/gui.h
- src/version.c
This fixes a issue related to konsole and terminals based on Konsole,
like cool retro terminal. If you exit the terminal before exiting nwipe,
nwipe will then continue running in the background but detached from any
terminals input/output. This causes a call to halfdelay()/getch() to
return immediately, thus removing the delay and causing the thread to
run at full speed causing 100% CPU in a core. This requires nwipe to
then be killed manually. This patch is related to the last patch in
that both patches do much the same thing but the previous patch fixes
the problem when nwipe is sitting at the drive selection screen, while
this patch fixes the problem during a wipe.
This problem would only be seen in specific KDE konsole related
terminals and only if you do not exit nwipe by using …
> Fix_nwipe_not_exiting_when_using_konsole

- src/logging.c
- src/nwipe.c
- src/version.c
If you use the --logfile option but specify a filename
that will be created in a directory that is not writable,
for instance, a system directory such as /proc/sys/ or
your current directory happens to be a system directory
that you are running nwipe from while not specifying a
writable path for the log file then nwipe would exit with
a segfault.
This is now fixed. If the logfile cannot be created
or opened, then a appropriate message is displayed and
nwipe is aborted.
> Fix obscure segfault when --logfile option used.

- src/gui.c
Replaced the mvwprintw command that contained an empty string with a simple increment to the line position which maintains the display as it was but gets rid of the -Wformat-zero-length string compiler warning.
> Fixes a compiler warning -Wformat-zero-length string

- README.md
I was searching for a DBAN alternative that runs in a normal Linux distro so I can hot-swap drives and not have to reboot the system. When I found nwipe, I went to install it in a grml live system. Turns out, nwipe ships with grml by default as you can see in [grml's dpkg.list](https://packages.grml.org/files/grml64-small_2021.07/dpkg.list).
It's not exactly the most up-to-date version (0.30-1+b2 for amd64) because grml is close to Debian stable. It even comes with the the small live system image.
> Add grml to distros that ship nwipe

- src/PDFGen/pdfgen.h
- src/context.h
- src/create_pdf.c
- src/create_pdf.h
- src/logging.c
1. Rearranged the layout so the Tech/ID signature is at the bottom of the report.
2. Added start date/time
3. Added end date/time
4. Changed data from helvetica to helvetica-bold
5. Created a definition for PDF_DARK_GREEN text in create_pdf.h and moved the previously created PDF_GRAY to create_pdf.h, to keep pdfgen.h vanilla.
6. Added the erasure status, ERASED, FAILED, ABORTED. ERASED in green and FAILED, ABORTED in red.
Further code to follow ..
> PDFGen5 - further work on PDF certificate

- src/create_pdf.c
- src/create_pdf.h
1. Change model/serial number in header to bold and move left slightly.
2. Create a filename for the report that identifies the wipe uniquely i.e:
nwipe_report_YY-MM-DD_HH-MM-SS_Model_XXXX_Serial_XXXX.pdf
3. Move size data 2 characters right to allow for up to two space prefix on size string. So data doesn't get written over the end of the 'Size:' label.
> PDFGen7 - further work on PDF certificate

- src/pass.c
1. Fix a bug in the static and random pass code where I unnecessarily moved the decrement of z (the count of bytes remaining) to after the periodic sync which meant every time it sync'ed z wasn't decremented due to r being used as a general results variable for the fdatasync function.
I prefer to just have a variable be responsible for just one thing hence my assumption r wasn't used for two different things.
Changed the position of the decrement of z, pass_done and round_done to their original position prior to the periodic sync.
> PDFGen11 - further work on PDF certificate

- src/context.h
- src/create_pdf.c
- src/device.c
- src/gui.c
- src/hpa_dco.c
- src/hpa_dco.h
- src/nwipe.c
- src/temperature.c
1. For devices that support HPA/DCO (not NVMe) nwipe displays the HPA status, it toggles every two seconds the size and the temperature i.e "[  1TB][ 35C]" with the HPA status such as [HPA disabled], [HPA ENABLED!], [HPA unknown]. The HPA ENABLED is highlighted with red text and a white background. HPA_disabled is standard white text on blue background.
More code to follow, a new option to be added, HPA, disable/enable which will disable the HPA and shut down the system. On manually powering back up the HPA should be reported as disabled.
Then lots of testing.
> HPA_DCO_003 - Add HPA,DCO capability

- src/create_pdf.c
- src/hpa_dco.h
1. Changes to colour on some items under certain conditions.
2. Changed the HPA labels to include DCO, and changed the text from HPA enabled/disabled to something more meaningful to a user, i.e Hidden area found, no hidden area.
3. Added a new define "HPA_NOT_SUPPORTED_BY_DRIVE" for recent SATA drives that no longer support HPA/DCO. Further work needs to be done determining whether a drive supports HPA/DCO or not in the hpa_dco.c functions.
more code to follow ..
Snapshot of part of the certificate showing a wipe that was started then aborted on a drive that has one sector (512bytes) hidden by the disk configuration overlay, the user having not chosen to restore the DCO, in order to expose the hidden area to the OS. Bytes erased shows the number of bytes erased before the user aborted the …
> PDFGen14 - further work on PDF certificate

- src/gui.c
- src/hpa_dco.c
- src/hpa_dco.h
1. In the GUI I switched the HPA/DCO status position from overlaying the [drive size][temp] and instead positioning the HPA/DCO status over the drive model and serial number. HPA/DCO information and drive details alternating every couple of seconds. This allowed me to extend the length of the HPA message and make it more meaningful to somebody that doesn't know the HPA/DCO terminology. Therefore "HPA Enabled" is replaced with "HPA/DCO Warning, hidden area detected"
2. Started adding bad/missing sense data detection ..
more code to follow ..
> HPA_DCO_004 - Add HPA/DCO Capability

- src/hpa_dco.c
- src/hpa_dco.h
- src/version.c
1. Created the function nwipe_read_dco_real_max_sectors() which directly accesses the disk drive sending a 0xB1 device configuration overlay identify command to the drive. We read the returned data structure extracting the real max sectors value. We do this if hdparm returns nonsense for the real max sector (as it does in hdparm v9.60) for some larger drives. This value is automatically sent to the nwipe log FYI.
2. Added a stdout & stderr pipe to the hdparm commands as verbose data appears to be sent to stderr, as we are interested in that data this pipe captures stderr as well as stdout.
3. Added headers "scsi/sg.h" and "scsi/scsi_ioctl.h" as we are now sending low level commands to the drives.
> HPA_DCO_005 - Add HPA/DCO capability

- src/gui.c
- src/hpa_dco.c
- src/logging.c
- src/logging.h
1. If nwipe enumerates a USB bridge that does not support ATA pass through or you are wiping a USB memory stick, nwipe will show a message in the GUI that says
"HPA/DCO hidden area indeterminate". If you get this message you know to either get yourself a better quality USB to SATA adapter or in the case of a USB memory stick, i've never come across one that supports HPA/DCO so either don't worry about it and wipe it as normal or physically destroy it.
2. We now check for a nonsense "real max sectors" as produced by the bug in hdparm. We use our own low level function to issue a DCO identify command and retrieve the correct value.
3. Changed the dmidecode info at the start of the log from a 'notice' classification to 'info'.
4. Made changes to the nwipe_log function so that any messages …
> HPA_DCO_006 - Add HPA/DCO capability

- src/create_pdf.c
- src/create_pdf.h
- src/device.c
- src/hpa_dco.c
- src/miscellaneous.c
- src/version.c
1. Added page 2 of the report which includes all smart data as displayed by smartctl -a /dev/sdx
2. Did some more work on the logic, i.e. when certain data on the certificate should be green and when it should be red.
3. Made some changes to nwipe's log in regards to the way it displays disc info right at the beginning of the log. Separated the drive information by a blank line to make each drive stand out from the rest.
4. Moved a string function from device.c to miscellaneous.c
[nwipe_report_2023-03-10-22-55-46_Model_ST350031_2CS_Serial_XXXXXXXXXXXXXXX.pdf](https://github.com/martijnvanbrummelen/nwipe/files/10946867/nwipe_report_2023-03-10-22-55-46_Model_ST350031_2CS_Serial_XXXXXXXXXXXXXXX.pdf)
more code to follow ..
> PDFGen15 - further work on PDF certificate

- src/gui.c
- src/nwipe.c
- src/temperature.c
- src/temperature.h
1. For each drive we now show the following temperature limits that are obtained directly from the drive. These are shown in the log under the INFO category. For a given drive all it's limits are shown on a single line near the start of the log. Whether all these values contain data will vary between manufacturer, for instance the Seagate SN570 only shows the high critical value of 84 deg.C
High critical - Exceeding this value can damage and/or reduce the life of the drive.
Highest - This is the maximum continuous running temperature allowed.
Lowest - This is the minimum continuous running temperature allowed.
Low critical - Dropping below this temperature may cause failure.
2. Changed some wording in the GUI for a on screen message to do with HPA/DCO.
> Add temperature limits to nwipe log

- src/gui.c
- src/gui.h
- src/version.c
Temperature text now changes red when it's exceeded the high critical temperature and black when it's dropped below the low critical temperature. See nwipes log for what those values actually are as those critical temperature values are obtained from each drive.
When the drive temperature is within the drives specification the temperature text will be white text on blue background.
The temperature text no longer flashes red or black.
> Fix anomaly with color change of temperature

- src/temperature.c
- src/version.c
Added the max and min drive temperatures to the nwipe log. We now have upto six temperatures that may be reported for each drive. Whether all these fields are populated is down to each drive manufacturer.
> Added max, min drive temperatures to log

- src/context.h
- src/gui.c
- src/temperature.c
- src/temperature.h
- src/version.c
Now validates temperatures rather than assuming the data is valid.
1. Checks for 0 in high critical and max.
2. Copes with missing critical or max min data or partially missing data.
3. Checks the high critical and max are the right way round
4. Checks the low critical and min are the right way round
5. Temperature is displayed in 5 different ways i. white text on blue - temperature with spec. (or no spec available) ii. red text on blue - max temperature reached.
iii. white text on red - critical high temperature reached. iv. black text on blue - minimum temperature reached. v. white text on black - critical low temperature reached.
Test code showing temperature cycling between +10 and -10 with critical at +8 and -8 and min/max at -5 & +5.
The colors of the temperature text and background …
> Validate temperatures.

- src/create_pdf.c
- src/gui.c
- src/hpa_dco.c
- src/nwipe.c
- src/version.c
1. Fix issue in PDF certificate where a drive that doesn't support device configuration overlay, shows 512 bytes as the disc size in the "Size(Real)" area on the certificate.
2. Fix a comment in the log that suggests you might be using a USB adapter or memory stick and those device can cause an indeterminate HPA/DCO status. This is now corrected so that we check the bus is USB before we issue that message.
3. Changes to some GUI text, replaced 'area' with 'sectors'.
4. Aligned "HPA/DCO No hidden sectors detected" to the drive model/serial text that it alternates with. One character left.
5. Nwipe's version and operating system information that is always printed to the console on exit, was not appearing in the optional log file, as optionally specified on the command line. This was caused …
> HPA_DCO_007 - Add HPA/DCO capability

- src/method.c
This bug only applies to ones wipe and one or zero's verification.
A very rare occurrence of a incorrect percentage on completion. The actual wipe was completed correctly it was just that the percentage calculation was wrong.
This was due to a variable that was initialised for all methods except ones, & ones & zeros verification.
For those three method's the uninitialised variable would have had to have the value 1 or 6 for the
incorrect percentage to be calculated, this is why it was so rare.
Corrected by initialising the variable with a -1 so that if no method was found in the array then no
extra calculations as regards the percentage are
performed.
> Fix obscure incorrect percentage on completion.

- src/context.h
- src/create_pdf.c
- src/device.c
- src/hpa_dco.c
- src/version.c
Many changes related to DCO real max sectors and HPA set and real sectors and how they are processed and used in the PDF creation function. More testing is required until I'm happy this works correctly with lots of different hardware including USB adapters that don't support DCO/HPA and also drives that don't support DCO/HPA such as the Seagate Enterprise EXOS drives.
> HPA_DCO_008 continuation of HPA/DCO integration.

- src/create_pdf.c
- src/miscellaneous.c
- src/miscellaneous.h
Changed the way percentage is calculated in the PDF report for bytes erased.
As we are dealing with large numbers and for some reason printf prints a double that is 99.99999999999 as
100.00 when a precision of two is specified I wrote a function that creates a percentage string such that 99.99999999999 is displayed as 99.99%. This is important in the report as a disc with one hidden sector will now correctly show as 99.99% erased and not 100.00% erased.
> HPA_DCO_009 Continuation of HPA/DCO integration.

- src/hpa_dco.c
- src/miscellaneous.c
- src/version.c
The Seagate EXOS family of drives don't support the ATA drive configuration overlay (DCO) command, however they do support host protected area (HPA). Therefore these drives can have hidden sectors.
The code was changed to accommodate the slightly different way these drives respond to a hdparm -N, that is, the response is accessible max address enabled or
accessible max address disabled. The new code correctly determines a the status of a drive in regards to
whether it has hidden sectors or not and what it's apparent and real size is.
> HPA_DCO_010 Continuation of HPA/DCO integration.

- src/hpa_dco.c
- src/version.c
Fixed a issue that occurs when a drive is attached via a USB adapter that doesn't correctly pass the ATA commands for HPA/DCO determination.
It incorrectly set the HPA_status as enabled when in fact it should have determined that DCO was accessible and a comparison against the size as returned by libata and the real max sectors which in this particular adapters case worked, was sufficient to correctly determine whether there were hidden sectors or not.
Now fixed, so HPA status is now determined correctly even on some less than ideal USB adapters.
> HPA_DCO_011 Continuation of HPA/DCO integration.

- src/context.h
- src/create_pdf.c
- src/device.c
- src/hpa_dco.c
- src/version.c
Simplified the code that determines whether a HPA/DCO is present and in the process fixed some related bugs to do with the HPA/DCO fields in the PDF document
displaying incorrect information in some drive specific cases.
> HPA_DCO_012 Continuation of HPA/DCO integration

- src/context.h
- src/create_pdf.c
- src/gui.c
- src/hpa_dco.c
- src/logging.c
- src/version.c
Fixes to apparent and real disc size fields in PDF based on use of c->Calculated_real_max_size_in_bytes.
Minor changes to HPA status messages for consistent messaging.
When HPA and DCO sector information cannot be obtained display the message "HPA/DCO data unavailable, can not determine hidden sector status" in the information field on the PDF.
Determine human readable size for the c->Calculated_real_max_size_in_bytes as used in the PDF real disc size field.
Instead of >>FAILURE!<< -1 when a I/O error occurs display >>IOERROR!<< -1 in the GUI.
> HPA_DCO_013 Continuation of HPA/DCO integration

- src/gui.c
- src/version.c
If you are running nwipe within the KDE konsole
terminal and you resize the window by pulling on
the corners, occasionally nwipe will exit with the error message:
"GUI.c,nwipe_gui_select(), loop runaway,
did you close the terminal without exiting nwipe?
Initiating shutdown now"
The loop runaway detection has been made less sensitive, i.e 32 iterations per second of the GUI update can now be completed before a loop runaway is detected. previously it was 8. In practise when sizing the konsole window, anywhere between 1 and 17 iterations will occur.
> Fix the premature exit when sizing konsole

- src/customers.c
- src/gui.c
Removed the csv field double quotes from the customer selection list as displayed on screen. The double quotes will still obviously exist in the csv file and are required for the code to work correctly in various places. However, for human readable text they are removed before displaying the customer details line on the selection screen as it makes the list look less 'busy' on screen hopefully.
I also fixed a issue where spaces were incorrectly being removed from the customer details when filtering for printable characters only.
> PDFGen27 Cleaned up customer selection list

- src/customers.c
- src/gui.c
When using backspace or esc to abort customer deletion, the first customer in the list would be incorrectly deleted. Corrected by this fix.
Also when aborting customer selection, the first customer in the list would be automatically selected. Also corrected by this fix.
> PDFGen29 Fix incorrect customer deletion/selection

- src/gui.c
- src/gui.h
Created a window that shows a preview of organisational, customer and date/time information that will be added to the PDF report. Items within the preview can be selected which takes you to the relevant window for editing the data. This can be optionally displayed before the drive selection window to make sure the data is correct before starting a wipe.
To complete this I need to add a further entry in the config window to allow editing date & time. Plus a function needs to be added to truncate the strings based on window width as some address strings could be wider than the window and mess up the display as they wrap to the next line.
> PDFGen30 Added org, customer & date/time preview

- src/gui.c
- src/gui.h
Created a function that truncates a string that is printed to a window if the string should exceed the window width.
This prevents the line wrap that occurs with mvwprintw when the window width is not wide enough. This mainly occurs with a 4:3 ratio monitor, 80 columns wide.
> PDFGen31 Created truncate string function

- src/logging.c
- src/nwipe.c
Under the following conditions a segfault will occur upon starting nwipe.
Run nwipe with --logfile option AND run nwipe in a directory that does not have write permissions so the logfile can't be created AND run nwipe without sudo or root or as as a user without sufficient privileges so you don't have permissions to write to the directory.
> Fix intermittent segfault when --logfile specified without insufficient permissions to write to directory

- src/device.c
- src/miscellaneous.c
- src/miscellaneous.h
- src/version.c
Some IDE USB adapter chipsets get the endian wrong for model name This fix identifies a endian swapped model name and corrects it.
The function currently only includes Samsung but I'll add more IDE drive manufacturers as I come across them.
This is peculiar to some USB IDE adapters. I've never seen this issue with SATA, ATA drives connected directly to the motherboard.
> fix_endian_model_name

- src/conf.c
- src/conf.h
- src/gui.c
- src/gui.h
- src/nwipe.c
- src/options.c
- src/options.h
Added new options in GUI config menu to display preview of organisation, customer, date/time at startup prior to drive selection. This preview is disabled as default but can be enabled in the config menu.
The purpose of the preview is to allow the user to check & update as required the organisation details, customer & current date/time so that the details provided on the PDF certificate/report are correct.
> PDFGen36_Add_Optional_Org_Customer_Preview_Prior_To_Drive_Selection.

- src/conf.c
- src/create_pdf.c
- src/create_pdf.h
Previously smart data was completely located on page 2 in two columns using a variable width font. This had two issues. The font size had to be very small to fit on the page which made it difficult to read and variable width fonts were used because the smart attribute table took up too much width when all the data was displayed in two newspaper type columns. This made the smart attribute table look messy.
This patch now displays the smart data over page two and three in mono spaced font and with a larger font size so it's easier to read and the columns with the smart attribute table are now aligned correctly.
In terms of the code, I placed the header and footer creation code in it's own function as this is called multiple times and will make it easier to add additional information pages …
> PDF_Gen37_single_column_smart_data

- src/device.c
- src/gui.c
The HPA message alternating with the drive model serial number made reading the serial number quite a challenge and made the display far too messy looking when displaying 20+ drives or even 10+ drives with differing HPA statuses.
Removed, alternating appearance.
Reduced size of message.
Placed after temperature, before drive model/serial in display.
> Change_HPA_message_to_stop_flashing_&_move_to_end_of_line

- src/gui.c
- src/nwipe.c
- src/temperature.c
- src/temperature.h
Due to significant delays in obtaining drive temperature from some drives especially SAS which was causing a noticeable freeze of a second or two or more in the GUI wipe status screen, being made worse the more drives that were being simultaneously wiped.
The temperature update code was separated from the GUI code by placing the temperature update in it's own thread.
> Temperature Thread

- src/logging.c
The message that logs which directory the nwipe PDF certificate is being saved, was being printed multiple times in the middle of the erasure summary table.
This was corrected so that it only prints once at the end of the table.
> Fix_message_creating_PDF_in

- src/options.h
Fixed the following warning:
create_pdf.c:795:18: warning: ‘/nwipe_report_’ directive output may be truncated writing 14 bytes into a region of size between 1 and 4096 [-Wformat-truncation=]
> Fix_warning_directive_output_may_be_truncated

- src/conf.c
Incorrectly trying to close a uninitialised file pointer stream when the file could not be opened.
> Fix_segfault_on_first_run_as_non_root

- src/nwipe.c
Checks user is running nwipe as root (required), if not exits with a warning message.
> Add_check_for_root_execution

- src/nwipe.h
Move the definition of the off64_t using int64_t  bellow the include stdint.h, which is actually defining it.
Without change wrong order is breaking the build on RHEL7/8/9.
> move the define off64_t

- configure.ac
Hello,
please lower the requirements to autoconf allowing to build rhel7/8 packages (possibly rhel6, not tested). Thank you
Michal Ambroz
> lower the build requirements

- src/gui.c
The definition of the newly used _POSIX_SOURCE affects preprocessing of the time.h. As result on RHEL7 (possibly 6 as well) the timespec structure is not defined.
Fixes bug #519
> move the include of time.h

- src/nwipe.c
so all the single letter disks (sda - sdz) appear before sdaa ...
> modified disk sorting for more than 26 disks

- src/context.h
- src/device.c
Added the abbreviation MMC for mmcblk devices such as SD and microSD cards and some low budget laptops.
Changed log message from "USB bridge, no pass-through support" to "Smart data unavailable" as no smart data could be caused by a non USB device such as mmcblk as well as USB devices with no ATA pass through and other devices that smartctl does not detect.
> Added mmcblk device type MMC

- src/gui.c
- src/version.c
If the user had blanked the screen, the autopoweroff and nowait options did not work. Instead they paused nwipe on completion of the wipe/s waiting for the b key to be pressed which reactivated compute_stats() function who's output indicates whether any wipes were still active.
This was fixed so that compute_stats() is always active while wipes are in progress irrespective of whether the screen is blanked or not. This is so that the nwipe_gui_status() function will exit assuming --autopoweroff or --nowait options have been used, when all the wipe threads have completed even if the screen has been blanked.
> Fix autopoweroff and nowait when screen blank

- src/nwipe.c
- src/version.c
Fix nwipe not auto exiting on completion in non gui mode.
This was caused by the temperature thread not exiting on completion of all wipes but this bug only occurred in non gui mode.
> Fix nwipe not auto exiting on completion in non gui mode.

- src/gui.c
Some of the config help messages that show the purpose of the keys were inconsistent or not updating correctly when going back to the previous menu. Now fixed.
> Fix the config help messages

- src/gui.c
This fixes incorrect footer text being displayed when Enable customer/company preview is enabled and the user select a field to be edited, completes the editing and returns to the preview to select A for accept. Only problem was A=Accept wasn't listed on the footer.
> Fix incorrect footer on return to preview

- src/gui.c
- src/logging.c
- src/options.c
- src/version.c
These changes solve three issues. The first issue was that it wasn't obvious that the PDFs are only created once you press return to exit after all the wipes have finished. It is now explicitly stated in the footer message if PDFs are enabled.
It also now specifies the logfile name on the footer if the user has specified a log file as a command line option. If no logfile is specified then STDOUT is displayed.
If the user specified --PDFreportpath=noPDF on the command line, prior to this commit it had no affect. This is now fixed so that it disables PDF's irrespective of what is in nwipe.conf. i.e command line options override the entries in nwipe.conf
If the user has specified a --PDFreportpath=noPDF=/some/path then PDF's are enabled irrespective of the value in nwipe.conf
> Make completion footer more informative

- src/context.h
- src/device.c
- src/hpa_dco.c
- src/version.c
This fixes an issue where nwipe detects a discrepancy between the number of sectors reported by hdparm and nwipe's own HPA/DCO functions that were reporting the same values, using number of sectors based on 512 byte sectors but disagreed with the number of sectors
generated from libata which was reporting the number of sectors based on 4096 byte sectors.
This has been fixed by always calculating the number of sectors returned by libata using 512 bytes per sector so a direct comparison can be made to data from hdparm & nwipe's HPA/DCO functions.
> Fix hidden sector detection for logical 4096 size

- src/context.h
- src/device.c
- src/hpa_dco.c
- src/nwipe.c
- src/version.c
Now populates the block size (physical) before
the hidden sector determination function runs.
The naming of block/sector can be very confusing in nwipe. So I have created a device_phy_sector_size
in the drive context, so we have
->device_sector_size // logical sector size
->device_phys_sector_size // physical sector size
->device_block_size // Usually the same as logical size but could be increased by nwipe to encompass
multiple logical sectors, i.e a block of sectors
> Populates device block size before hidden sector

- configure.ac
- man/nwipe.1
- src/device.c
- src/version.c
Replace three strcpy commands with strncpy,
bump minor version ready for more testing.
> Fix some strcpy compiler warnings

- src/mt19937ar-cok/mt19937ar-cok.c
- src/mt19937ar-cok/mt19937ar-cok.h
Necessary for further implementation of AES and SHA algorithms, due to conflicting const naming in `mt19937ar-cok.h` and `mt19937ar-cok.c`
> Renamed N and M to MT_STATE_SIZE and MT_MIDDLE_WORD due to const naming of mt19937ar-cok.h, causing conflicts with SHA-512 HMAC's libssl.

- src/pass.c
Based on the Valgrind output, I noticed an "Invalid read of size 1" error occurring in the `nwipe_random_pass` function. After inspecting the relevant portions of the source code, it seems like the issue is related to an off-by-one error where my code attempts to access memory just outside the allocated buffer.
```
Thread 4:
==6062== Invalid read of size 1
==6062==    at 0x4117BC: nwipe_random_pass (pass.c:328)
==6062==    by 0x415EFC: nwipe_runmethod (method.c:934)
==6062==    by 0x417029: nwipe_random (method.c:742)
==6062==    by 0x4E98946: start_thread (pthread_create.c:444)
==6062==    by 0x4F1E873: clone (clone.S:100)
==6062==  Address 0x539da20 is 0 bytes after a block of size 4,096 alloc'd
==6062==    at 0x4849E60: calloc (vg_replace_malloc.c:1595)
==6062==    by 0x4115FE: …
```
> Fixed memory leak in line 328, writing 1 byte beyond allocated memory.

- src/options.c
For legacy 32-bit systems, such as a Pentium 2, selecting an appropriate pseudo-random number generator (PRNG) is crucial for ensuring both performance and quality of randomness. When comparing the Xoroshiro256 algorithm with a Lagged Fibonacci Generator (LFG) utilizing subtraction and carry, several factors come into play, especially regarding performance on such dated hardware.
1. **Xoroshiro256** is part of the Xoroshiro/Xoshiro family, known for its speed and excellent statistical properties. However, its implementation typically relies on 64-bit arithmetic operations to achieve optimal performance, which is not ideal on 32-bit systems. On such systems, 64-bit operations are internally broken down into multiple steps, leading to a decrease in performance.
2. **Lagged Fibonacci …
> XORoshiro-256 and ALFG as default PRNG for 64-Bit and 32-Bit platforms. Also PRNG method as default method.

- src/hpa_dco.c
This fixes a valgrind detected error. We check that the number of real max sectors is greater than zero before incrementing the value by 1. However occasionally the ioctl call may not be able to obtain the dco and therefore the ioctl data block is never populated. By zeroing the data block prior to use and if it is not populated by the ioctl call then the calculated real max sectors will be zero and no increment will occur which is what we want.
> Fix conditional jump on uninitialised value

- configure.ac
PKG_CHECK_MODULES needs all modules in a single list or else the following error message appears during configure run:
`  ./configure: 6807: libconfig: not found`
because the macro interprets "[libconfig]" as the action that needs to be done if parted was found.
> configure.ac: Fix check for parted

- README.md
Added DiskDump, a Debian Livecd designed for eMMC chips.
https://github.com/Awire9966/DiskDump
> Added DiskDump

- src/gui.c
If nwipe used within ShredOS, the d key will toggle the font size, has no action for other xorg/wayland distributions.
> toggle font size for tty terminal based use with d key. Not relevant for xorg/wayland based use.

- src/xor/README.md
- src/xor/XOROSHIRO_PROOF_OF_CONCEPT.md
Ahoy,
This one i forgot in the first PR, but i consider it to be important, as XORoshiro-256 is a heavily modified and not-yet existing adaption of XORoshiro-128**.
Added detailed documentation for the XORoshiro-256 PRNG implementation, including a comprehensive README and a formal paper outlining the mathematical and statistical analysis in the `src/xor` folder. 
The README explains key differences between XORoshiro-256 and the original XORoshiro-128**, its optimization for nwipe, and usage recommendations. The accompanying paper provides an in-depth exploration of entropy propagation, performance considerations, and empirical test results. 
This update formalizes the implementation and supports its use in non-cryptographic applications with high throughput requirements on 64-bit …
> Added XORoshiro-256 PRNG implementation paper and README with detailed behaviour

- src/create_pdf.c
Fix mini typo on PRNG algorithm: XORoshiro256 is missing an "o"
> Fix typo in create_pdf.c

- src/hpa_dco.c
This patch fixes the problem so that a SAS drive responds with hidden sectors = not applicable.
A SATA drive connected to a SAS interface should still respond with yes or no subject to the interface passing HPA and DCO-identify commands.
> Fixes a issue where SAS drives always respond with hidden sectors = ??? , i.e a warning.

- src/create_pdf.c
- src/device.c
- src/hpa_dco.c
- src/nwipe.c
The new search location is /usr/sbin/. Previously we searched /sbin/ and /usr/bin/ but /sbin is symbolically linked to /usr/sbin/ so just in case there was some issue with the symbolic link we also now search /usr/sbin/
> Add a new search location when looking for hdparm and smartctl.

- src/miscellaneous.c
This patch fixes model names for Hitachi, Toshiba, WDC Western Digital Corporation and Seagate/ST drives when used with some USB adapters that get the endian incorrect for model name and serial number. Mainly older adapters and drive interfaces.
> Fix endian for various model names on some older USB adapters

- src/miscellaneous.c
Fixes a buffer overflow in the last commit. That earlier commit added additional model names to the endian model swap code but did not calloc suffient storage for the termination character.
> Fixes a buffer overflow

- src/miscellaneous.c
Fix missing trailing character on odd model lengths. Remove unnecessary +1 from length calculation (strlen). Remove debug nwipe_log message
> Tidy up endian swap code

- src/gui.c
- src/version.c
This is only relevant to ShredOS and is disabled for other distros, as doubling font size is controlled within the terminal or window management of the distro.
When nwipe detects ShredOS it makes an additional command available to the GUI in the drive selection window and progress window (after the wipe has started) This command is 'f'. Pressing the f key whether in drive selection or progress windows will double the size of the font. Pressing 'f' again will toggle the font size back to it's original size.
In addition and depending on whether ShredOS is detected, it will add an additional item to the help footer of both the drive selection and progress windows. e.g. f=Font size
> ShredOS specific patch to toggle font size

- src/gui.c
The s shift s bug is reported here
https://github.com/PartialVolume/shredos.x86_64/issues/301
To summarize, if no drives are selected and then the user presses s (lower case) a warning appears indicating that the user should press S (upper case) to start the wipe. This warning appears for about 3 seconds but during this time if the user presses S (upper case) nwipe would immediately complete, having wiped no drives and requesting the user to press the spacebar to exit. The is incorrect behaviour.
The bug doesn't appear if the user pressed S after the 3 seconds elapsed and the warning message disappeared.
This patch fixes this so that it does not exit but displays the warning for 3 seconds and then waits for input.
> Fixes the s shift s bug

- src/gui.c
- src/method.c
- src/method.h
- src/options.c
- Added a new wiping method following the Bruce Schneier 7-Pass standard.
- Overwrites the device with:
- Pass 1: All ones (0xFF)
- Pass 2: All zeroes (0x00)
- Pass 3-7: Five passes of PRNG-generated random data.
- Updated method.h with the function prototype for `nwipe_bruce7`.
- Added `nwipe_bruce7()` implementation in method.c.
- Registered method label in `nwipe_method_label()`.
- Updated UI in options.c to display security level and details.
> Implement Bruce Schneier 7-Pass wiping method
